# https://github.com/pmarsceill/just-the-docs/blob/master/_config.yml

title: remoteStorage
description: Open protocol for per-user storage on the Web
repository: remotestorage/website
theme: just-the-docs
permalink: pretty
search_enabled: false

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/remotestorage/website" # the github URL for your repo
gh_edit_branch: "master" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "edit" # "tree" or "edit" if you want the user to jump into the editor immediately
